compatibility_date = "2024-02-18"
node_compat = true
[vars]
DB_USERNAME = "kanbanboard_user"
DB_HOST = "postgres://kanbanboard_user:AmIzK4WEdMS0IH0IvjjncOOfOxCzOgHq@dpg-cn8uqmi1hbls73dd8dl0-a.oregon-postgres.render.com/kanbanboard"
DB_PASSWORD="AmIzK4WEdMS0IH0IvjjncOOfOxCzOgHq"
DB_PORT = "5432"
DB_NAME = "kanbanboard"
JWT_SECRET= "5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8"